<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711205847 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, type VARCHAR(255) NOT NULL, starting_balance DOUBLE PRECISION NOT NULL, starting_basis DOUBLE PRECISION DEFAULT NULL, annual_return_rate DOUBLE PRECISION NOT NULL, inflation_rate DOUBLE PRECISION NOT NULL, horizon_years INT NOT NULL, contribution_monthly_amount DOUBLE PRECISION NOT NULL, contribution_escalation_rate DOUBLE PRECISION NOT NULL, contribution_starts_on DATE DEFAULT NULL, contribution_ends_on DATE DEFAULT NULL, drawdown_amount DOUBLE PRECISION DEFAULT NULL, drawdown_frequency VARCHAR(255) NOT NULL, drawdown_entry_mode VARCHAR(255) NOT NULL, drawdown_starts_on DATE DEFAULT NULL, drawdown_ends_on DATE DEFAULT NULL, drawdown_inflation_indexed BOOLEAN DEFAULT true NOT NULL, portfolio_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D3656A4B96B5643 ON account (portfolio_id)');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4B96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A4B96B5643');
        $this->addSql('DROP TABLE account');
    }
}
